name: Main Branch Deployment

on:
  push:
    branches:
      - dev1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Secret 1
        run: echo ${{ secrets.SECRET_1 }}

      - name: Use Secret 2
        run: echo ${{ secrets.SECRET_2 }}

      # Add your deployment steps here
      # For example, if you're deploying a web server:
      - name: Start web server
        run: |
          # Command to start your web server, e.g., npm start, python app.py, etc.
